{% set name = "freetype-py" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: cfe2686a174d0dd3d71a9d8ee9bf6a2c23f5872385cf8ce9f24af83d076e2fbd

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=42
    - setuptools_scm >=3.4
    - tomli
    - freetype {{ freetype }}
  run:
    - python
    - freetype

test:
  source_files:
    - tests
    - examples
  requires:
    - pip
    - pytest
  imports:
    - freetype
  commands:
    - pip check
    - pytest tests/smoke_test.py tests/vf_test.py -v

about:
  home: https://github.com/rougier/freetype-py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python binding for the freetype library
  description: |
    Freetype Python provides bindings for the FreeType library.
    Only the high-level API is bound.
  doc_url: https://freetype-py.readthedocs.io/
  dev_url: https://github.com/rougier/freetype-py

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
