travis:
  secure:
    BINSTAR_TOKEN: j8Kb+s0ruT7yB4YPXpXlcOTHba9o/xwxqYx5axMwVUrJjWs4eKmgzZeBwasL9VaveL7NMm8EzYFkcg6lA0Ew0IjH+dUauooZmejPP00g6r95hYsq1Edmce3f5wsjmapC7a8JwhQoIl9YtwXvNZmEpFkwoKU3HhdiUGIq3GH0XuOY4VeiWTOXWZqGUzHS1vL8VBCuT8Yc3BSvzwPuEiEC79tpWUsSAX3FVlyhNfZWnwrWO8k1TODxIsUvtmTjAmkx3/lKP6pa4v1OSBYf+WtL8RtnfqD17EHQCAUtkAwuMTUMJGzf57JU4WKJtdENtb7zF0HOwGEK+cKmWiifeK6UQPPJdmMBhvyiH0aqzqRsAhAVT/V7JmNYtvb5H3l3EVyEGXpB9/6CuQKdIfJ/mFaGg3aPTutLPb2LAcfS3+sYzBYR+hCS7YysYvWpI1rkZ6WN02CEtwguyDcnLbOsQO+zBrU3QlCA4aSNpEallJUPgL544R48t823chYHxn9uwdzzom4eGZBf0IM9QE7OgAmSyi8nFNzmJsp2h0aR+8gzea5wYO1p1ujfpxJJKxONrb2qDc2TzDKT0TP23VWrOW9J/GcDNdX32hH2b8YyrIyDoB0f8KXcWLQS9IHDf3VSr3Kmc/Q/BeAJnM503Z9/lZyQ/JmGdrg+wcweargPa9tNd7M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
